# Generated by Django 5.0.6 on 2024-07-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название поста",
                        max_length=100,
                        verbose_name="Наименование поста",
                    ),
                ),
                (
                    "slug",
                    models.TextField(
                        blank=True,
                        help_text="Добавьте описание продукта",
                        null=True,
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Добавьте текст поста",
                        null=True,
                        verbose_name="Текст поста",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для поста",
                        null=True,
                        upload_to="catalog/images",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Генерируется автоматически",
                        verbose_name="Дата создания поста",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        help_text="Укажите, будет ли пост опубликован",
                        verbose_name="Маркер публикации/архивации поста",
                    ),
                ),
                (
                    "views_amount",
                    models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["created_at"],
            },
        ),
    ]
