# Generated by Django 5.0.6 on 2024-07-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Укажите, будет ли пост опубликован",
                verbose_name="Маркер публикации/архивации поста",
            ),
        ),
    ]
