# Generated by Django 5.0.6 on 2024-07-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение для поста",
                null=True,
                upload_to="blog/images",
                verbose_name="Фото",
            ),
        ),
    ]
