# Generated by Django 5.0.6 on 2024-07-17 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                help_text="Добавьте дату создания продукта",
                verbose_name="Дата создания продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                auto_now=True,
                default=django.utils.timezone.now,
                help_text="Добавьте дату изменения продукта",
                verbose_name="Дата последнего изменения продукта",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Укажите номер версии продукта",
                        verbose_name="Номер версии",
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="Укажите название версии",
                        max_length=100,
                        verbose_name="Наименование версии",
                    ),
                ),
                (
                    "is_current_version",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, является ли текущей версией продукта",
                        verbose_name="Текущая версия",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продуктов",
                "ordering": ["-version_number"],
            },
        ),
    ]
