# Generated by Django 4.2.2 on 2024-07-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price"],
                "permissions": [
                    ("can_cancel_publication", "Can cancel publication"),
                    ("can_edit_description", "Can edit description"),
                    ("can_change_category", "Can change category"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Укажите, будет ли продукт опубликован",
                verbose_name="Маркер публикации/архивации продукта",
            ),
        ),
    ]
